[package]
name = "execute"
version = "0.1.0"
authors = ["Leonardo Delfino"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
took = "0.1.2"

# Days
day01a = { path = "../day01a" }
day01b = { path = "../day01b" }
